services:
  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: unless-stopped
    networks:
      - guacnet

  db:
    image: mysql:9.4
    container_name: guac-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - guacnet

  guacamole:
    image: guacamole/guacamole
    container_name: guac
    restart: unless-stopped
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: db
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole
    depends_on:
      - guacd
      - db
    ports:
      - "8080:8080"
    networks:
      - guacnet

networks:
  guacnet:
    driver: bridge
